### ISSUE TITLE
Still not finding binaries after latest release

### ISSUE THREAD

**Issue by NikosFotiadis** [vercel/pkg-fetch#132]
Error from docker
```
> pkg@4.5.0
> Fetching base Node.js binaries to PKG_CACHE_PATH

> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v14.16.0-alpine-x64
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v14.16.0-alpine-x64"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v14.16.0-alpine-x64"}
> Building base binary from source:
  built-v14.16.0-alpine-x64
> Error! Not able to build for 'alpine' here, only for 'linux'
```

Using the exact same code I was using to build before the latest release. It was working fine until then.

I am targeting alpine. This is the command I am using
```
pkg ./index.js --output exec --targets alpine
```

**Comment by robertsLando** [comment]
The error is not due to the last bug, it is because that version is not actually present

**Comment by NikosFotiadis** [comment]
Yes, I can see that. I opened an issue on the pkg repo as well [#1098](https://github.com/vercel/pkg/issues/1098)

**Comment by NikosFotiadis** [comment]
According to the latest release there is now support for `14.16.0`, so shouldn't that binary be there?

**Comment by robertsLando** [comment]
Exactly, the problem is that we have added patches but not binaries yet. This means that in order to compile again you should specify the full node version like 14.4.0 (choose one that has an existing binary).

By default when you just specify major pkg-fetch will take latest major based on the patches available.

@leerob @jesec @hipstersmoothie I think we could make a fix for this and automatically downgrade to the first binary available if latest is not present? Also we should decide how to handle pkg-fetch releases, we could make it search through previous releases too in order to avoud the problem encountered in 2.7.0

**Comment by hipstersmoothie** [comment]
I think searching previous releases is fine. We could also just copy all the binaries from the last release to latest when it's made

**Comment by jesec** [comment]
We are not supposed to release recent changes before the binaries are ready.

No, we shall not add any fallback mechanism. That just won't happen if things are done correctly. A fallback mechanism introduces non deterministic elements. People are going to complain that `pkg` is not using the latest binaries in some cases. 

Plus, it is just PITA to figure out the next available version (going to require Github API call or something) .

**Comment by robertsLando** [comment]
I would focus on building missing binaries so. In my repo I have builded 14.16 arm64 and 12.21 arm64 

https://github.com/yao-pkg/pkg-binaries/releases

@leerob If you want you could download them and add to release assets
