### ISSUE TITLE
node-v14.17.0-macos-x64 hardcoded hash mismatch in 3.2

### ISSUE THREAD

**Issue by schlomo** [vercel/pkg-fetch#201]
https://github.com/vercel/pkg-fetch/blob/b30cbad6ea4297dcc28a2024e322971ec7e49c0b/lib/expected.ts#L82
https://github.com/vercel/pkg-fetch/blob/b30cbad6ea4297dcc28a2024e322971ec7e49c0b/lib/expected.ts#L83

```shell
$ shasum -a 256 -c node-v14.17.0-macos-x64.sha256sum
node-v14.17.0-macos-x64: OK
$ cat node-v14.17.0-macos-x64.sha256sum
074a517cbf9a5abd2faa976426eeea37fb7a0cf976e4441b757deac2b66beb8a  node-v14.17.0-macos-x64
```

The hardcoded hash for `node-v14.17.0-macos-x64` doesn't match the binary and also not the sha256 file next to the binary in the 3.2 release, breaking builds.

**Comment by jesec** [comment]
Since 3.2 does not have any real user (pending vercel/pkg#1215), I disregarded some versioning conventions when I prepare 3.2.1 bugfix release, and the impacted binaries are not useable anyways due to the bug. 

Unfortunately, it seems that both @leerob and I are busy last few weeks, and we forgot to publish the release to npm. So yeah, this happens. 

I am preparing 3.3, and hopefully we can have a new release in the next few days.

**Comment by jesec** [comment]
@leerob 

On second thought, for the sake of correctness, I think we should still publish 3.2.1. Can you publish 3.2.1 to npm when you have time? It is already tagged on Github.

**Comment by sgoll** [comment]
> On second thought, for the sake of correctness, I think we should still publish 3.2.1. Can you publish 3.2.1 to npm when you have time? It is already tagged on Github.

I second that. `3.2.0` is currently breaking our macOS builds as well.

**Comment by leerob** [comment]
Sure, I can do that.

**Comment by jesec** [comment]
@schlomo Please check out the new release, and feel free to close the issue if it works.

**Comment by schlomo** [comment]
I can confirm that this fix works, thanks a lot!
