### ISSUE TITLE
node-v14.17.0-macos-arm64 is broken

### ISSUE THREAD

**Issue by umireon** [vercel/pkg-fetch#211]
I couldn't execute node-v14.17.0-macos-arm64 on my M1 Mac.

Tested on M1 Mac.

```
% curl -fsSLO https://github.com/vercel/pkg-fetch/releases/download/v3.2/node-v14.17.0-macos-arm64
% chmod a+x node-v14.17.0-macos-arm64
% ./node-v14.17.0-macos-arm64
zsh: killed     ./node-v14.17.0-macos-arm64
```

```
% file ./node-v14.17.0-macos-arm64
./node-v14.17.0-macos-arm64: Mach-O 64-bit executable arm64
```

**Comment by jesec** [comment]
No, it is not. Please read https://github.com/vercel/pkg#targets again. 

> `macos-arm64` is experimental. Be careful about the [mandatory code signing requirement](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-universal-apps-release-notes).
The final executable has to be signed (ad-hoc signature is sufficient) with `codesign`
utility of macOS (or `ldid` utility on Linux). Otherwise, the executable will be killed
by kernel and the end-user has no way to permit it to run at all. `pkg` tries to ad-hoc
sign the final executable. If necessary, you can replace this signature with your own
trusted Apple Developer ID.

**Comment by umireon** [comment]
Oh sorry, this is my bad🙇‍♀️
