### ISSUE TITLE
need to enable support to node LTS 18.14.1

### ISSUE THREAD

**Issue by jose-p-rivera** [vercel/pkg-fetch#275]

**Comment by baparham** [comment]
Can you clarify what you mean? Are you referring to a patch set for 18.14.0? Do you mean for CI runner support?

Node.js is releasing new builds today or tomorrow so it's probably not worth the effort to do 18.14.0, but rather jump straight to whatever they release next since that will fix some OpenSSL CVEs too.

**Comment by baparham** [comment]
If it's for patches, this is covered by #277

**Comment by jose-p-rivera** [comment]
thanks @baparham
