### ISSUE TITLE
Missing macos-x86 binaries, can't compile for win-x86

### ISSUE THREAD

**Issue by flocca** [vercel/pkg-fetch#68]
In version 2.6 binaries for macos-x86 are not provided. It's now impossible to target win-x86 from macOS (macos-x86 is required but not found).

**Comment by FabianTe** [comment]
I am having a similar problem. Can't build for `win-x86` because `https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v10.15.3-linux-x86` does not exist.

**Comment by FabianTe** [comment]
I guess this relates to: https://github.com/zeit/pkg-fetch/pull/60

**Comment by danthegoodman** [comment]
I also came across this issue.

Here are some workarounds that won't change pkg's output:

1. Find a way to build and supply your own version of node, compiled in 32-bit mode. I have no idea how feasible this is.
2. Build your pkg targeting a 32-bit machine from a windows machine with the 32-bit version of node
3. Stop distributing a 32-bit version of your package.

Alternatively, if you're comfortable with shipping your source code instead of having it compiled into a binary format, you can disable that feature by passing the following arguments to pkg:

```
--no-bytecode --public --public-packages '*'
```

**Comment by gokaybiz** [comment]
Same issue on linux.
